# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myGUIWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1689, 907)
        font = QtGui.QFont()
        font.setFamily("Heiti TC")
        font.setBold(True)
        font.setWeight(75)
        mainWindow.setFont(font)
        mainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(360, 20, 1292, 812))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rightEyeImg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rightEyeImg.setMinimumSize(QtCore.QSize(640, 400))
        self.rightEyeImg.setMaximumSize(QtCore.QSize(640, 400))
        self.rightEyeImg.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.rightEyeImg.setObjectName("rightEyeImg")
        self.gridLayout.addWidget(self.rightEyeImg, 0, 1, 1, 1)
        self.leftEyeImg = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftEyeImg.sizePolicy().hasHeightForWidth())
        self.leftEyeImg.setSizePolicy(sizePolicy)
        self.leftEyeImg.setMinimumSize(QtCore.QSize(640, 400))
        self.leftEyeImg.setMaximumSize(QtCore.QSize(640, 400))
        self.leftEyeImg.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.leftEyeImg.setObjectName("leftEyeImg")
        self.gridLayout.addWidget(self.leftEyeImg, 0, 0, 1, 1)
        self.depthImg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.depthImg.setMinimumSize(QtCore.QSize(640, 400))
        self.depthImg.setMaximumSize(QtCore.QSize(640, 400))
        self.depthImg.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.depthImg.setObjectName("depthImg")
        self.gridLayout.addWidget(self.depthImg, 1, 0, 1, 1)
        self.resultImg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.resultImg.setMinimumSize(QtCore.QSize(640, 400))
        self.resultImg.setMaximumSize(QtCore.QSize(640, 400))
        self.resultImg.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.resultImg.setObjectName("resultImg")
        self.gridLayout.addWidget(self.resultImg, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(70, 400, 241, 126))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Heiti TC")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.Area = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Area.setEnabled(False)
        self.Area.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.Area.setObjectName("Area")
        self.gridLayout_2.addWidget(self.Area, 4, 1, 1, 1)
        self.coordinate_x = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.coordinate_x.setEnabled(False)
        self.coordinate_x.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.coordinate_x.setObjectName("coordinate_x")
        self.gridLayout_2.addWidget(self.coordinate_x, 0, 1, 1, 1)
        self.coordinate_z = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.coordinate_z.setEnabled(False)
        self.coordinate_z.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.coordinate_z.setObjectName("coordinate_z")
        self.gridLayout_2.addWidget(self.coordinate_z, 2, 1, 1, 1)
        self.coordinate_y = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.coordinate_y.setEnabled(False)
        self.coordinate_y.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.coordinate_y.setObjectName("coordinate_y")
        self.gridLayout_2.addWidget(self.coordinate_y, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Heiti TC")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 80, 171, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pBtn_readEyeImg = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_readEyeImg.sizePolicy().hasHeightForWidth())
        self.pBtn_readEyeImg.setSizePolicy(sizePolicy)
        self.pBtn_readEyeImg.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_readEyeImg.setFont(font)
        self.pBtn_readEyeImg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pBtn_readEyeImg.setMouseTracking(False)
        self.pBtn_readEyeImg.setObjectName("pBtn_readEyeImg")
        self.verticalLayout.addWidget(self.pBtn_readEyeImg)
        spacerItem1 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.pBtn_getDepthImg = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_getDepthImg.sizePolicy().hasHeightForWidth())
        self.pBtn_getDepthImg.setSizePolicy(sizePolicy)
        self.pBtn_getDepthImg.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_getDepthImg.setFont(font)
        self.pBtn_getDepthImg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pBtn_getDepthImg.setObjectName("pBtn_getDepthImg")
        self.verticalLayout.addWidget(self.pBtn_getDepthImg)
        spacerItem2 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.pBtn_getBestArea = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_getBestArea.sizePolicy().hasHeightForWidth())
        self.pBtn_getBestArea.setSizePolicy(sizePolicy)
        self.pBtn_getBestArea.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_getBestArea.setFont(font)
        self.pBtn_getBestArea.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pBtn_getBestArea.setObjectName("pBtn_getBestArea")
        self.verticalLayout.addWidget(self.pBtn_getBestArea)
        spacerItem3 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.pBtn_refresh = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_refresh.sizePolicy().hasHeightForWidth())
        self.pBtn_refresh.setSizePolicy(sizePolicy)
        self.pBtn_refresh.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_refresh.setFont(font)
        self.pBtn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pBtn_refresh.setObjectName("pBtn_refresh")
        self.verticalLayout.addWidget(self.pBtn_refresh)
        spacerItem4 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.pBtn_dynamic = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_dynamic.sizePolicy().hasHeightForWidth())
        self.pBtn_dynamic.setSizePolicy(sizePolicy)
        self.pBtn_dynamic.setObjectName("pBtn_dynamic")
        self.verticalLayout.addWidget(self.pBtn_dynamic)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(70, 560, 181, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.slider_num = QtWidgets.QSlider(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_num.sizePolicy().hasHeightForWidth())
        self.slider_num.setSizePolicy(sizePolicy)
        self.slider_num.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slider_num.setMinimum(1)
        self.slider_num.setMaximum(10)
        self.slider_num.setPageStep(2)
        self.slider_num.setOrientation(QtCore.Qt.Horizontal)
        self.slider_num.setObjectName("slider_num")
        self.gridLayout_3.addWidget(self.slider_num, 1, 1, 1, 1)
        self.slider_BlockSize = QtWidgets.QSlider(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_BlockSize.sizePolicy().hasHeightForWidth())
        self.slider_BlockSize.setSizePolicy(sizePolicy)
        self.slider_BlockSize.setMinimumSize(QtCore.QSize(5, 0))
        self.slider_BlockSize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slider_BlockSize.setMinimum(5)
        self.slider_BlockSize.setMaximum(100)
        self.slider_BlockSize.setSingleStep(2)
        self.slider_BlockSize.setOrientation(QtCore.Qt.Horizontal)
        self.slider_BlockSize.setObjectName("slider_BlockSize")
        self.gridLayout_3.addWidget(self.slider_BlockSize, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Heiti TC")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Heiti TC")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_blocksize = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_blocksize.sizePolicy().hasHeightForWidth())
        self.label_blocksize.setSizePolicy(sizePolicy)
        self.label_blocksize.setMinimumSize(QtCore.QSize(10, 10))
        self.label_blocksize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_blocksize.setObjectName("label_blocksize")
        self.gridLayout_3.addWidget(self.label_blocksize, 0, 2, 1, 1)
        self.label_num = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_num.sizePolicy().hasHeightForWidth())
        self.label_num.setSizePolicy(sizePolicy)
        self.label_num.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_num.setObjectName("label_num")
        self.gridLayout_3.addWidget(self.label_num, 1, 2, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1689, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.slider_BlockSize.sliderMoved['int'].connect(self.label_blocksize.setNum)
        self.slider_num.sliderMoved['int'].connect(self.label_num.setNum)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "利用深度图寻找最佳降落位置"))
        self.rightEyeImg.setText(_translate("mainWindow", "TextLabel"))
        self.leftEyeImg.setText(_translate("mainWindow", "TextLabel"))
        self.depthImg.setText(_translate("mainWindow", "TextLabel"))
        self.resultImg.setText(_translate("mainWindow", "TextLabel"))
        self.label_2.setText(_translate("mainWindow", "最佳降落区域面积"))
        self.label.setText(_translate("mainWindow", "最佳降落区域中心坐标"))
        self.pBtn_readEyeImg.setText(_translate("mainWindow", "读取双目图像"))
        self.pBtn_getDepthImg.setText(_translate("mainWindow", "计算深度图"))
        self.pBtn_getBestArea.setText(_translate("mainWindow", "计算最佳降落位置"))
        self.pBtn_refresh.setText(_translate("mainWindow", "清空显示"))
        self.pBtn_dynamic.setText(_translate("mainWindow", "动态显示"))
        self.label_3.setText(_translate("mainWindow", "BlockSize"))
        self.label_4.setText(_translate("mainWindow", "Num"))
        self.label_blocksize.setText(_translate("mainWindow", "5"))
        self.label_num.setText(_translate("mainWindow", "1"))

